[build]
  functions = "netlify/functions"

[functions]
  # esbuild 대신 Netlify 기본 번들러(nft) 명시
  node_bundler = "nft"
  # 처음 에러가 났던 axios 모듈을 배포 파일에 강제로 포함
  included_files = ["node_modules/axios/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200